version: "3"

services:
  gcs-mock:
    image: fsouza/fake-gcs-server
    volumes:
      - "./data:/data"

  wrangler:
    depends_on: ["gcs-mock"]
    build:
      context: ./wrangler
      dockerfile: devtest.dockerfile
    environment:
      - GCP_API_HOST=https://gcs-mock:4443
      - MIX_ENV=integration
    volumes:
      - ./wrangler:/app
      #- ./wrangler/config:/app/config
      #- ./wrangler/lib:/app/lib
      #- ./wrangler/test:/app/test
      #- ./wrangler/_build:/app/_build
      #- ./wrangler/bin:/app/bin
      #- ./wrangler
    command: tail -f /dev/null

