version: "3"

services:
  gcs-mock:
    image: fsouza/fake-gcs-server
    volumes:
      - "./data:/data"

  wrangler:
    depends_on: ["gcs-mock"]
    build:
      context: ./wrangler
      dockerfile: devtest.dockerfile
    environment:
      - GCP_API_HOST=https://gcs-mock:4443
    command: ./bin/test

