version: "3"

services:
  gcs-mock:
    image: fsouza/fake-gcs-server
    volumes:
      - "./data:/data"

  wrangler:
    depends_on: ["gcs-mock"]
    image: michaeldbianchi/wrangler:dev
    build:
      context: ./wrangler
      dockerfile: devtest.dockerfile
    environment:
      - GCP_API_HOST=https://gcs-mock:4443
    volumes:
      - ./wrangler:/app
    command: tail -f /dev/null
