[package]
name = "parquetserializer"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "parquetserializer"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
parquet = "0.16.0"
